hobby_categories = [
    ['outdoor', 'hiking', 'camping', 'gardening', 'running', 'cycling', 'birdwatching', 'fishing', 'kayaking', 'surfing'],
    ['sports', 'basketball', 'football', 'tennis', 'volleyball', 'swimming', 'golf', 'soccer', 'baseball', 'badminton'],
    ['arts', 'painting', 'drawing', 'photography', 'sculpting', 'calligraphy', 'pottery', 'origami', 'weaving', 'printmaking'],
    ['music', 'guitar', 'piano', 'singing', 'drums', 'violin', 'ukulele', 'flute', 'trumpet', 'bass'],
    ['cooking', 'baking', 'grilling', 'sushi-making', 'cake decorating', 'cocktail mixing', 'fermentation', 'chocolate-making', 'barbecuing', 'pizza-making'],
    ['gaming', 'video games', 'board games', 'card games', 'puzzle games', 'role-playing games', 'online gaming', 'strategy games', 'word games', 'arcade games'],
    ['reading', 'fiction', 'non-fiction', 'mystery', 'fantasy', 'biography', 'poetry', 'romance', 'thriller', 'science fiction'],
    ['fitness', 'yoga', 'pilates', 'meditation', 'zumba', 'crossfit', 'aerobics', 'kickboxing', 'spinning', 'strength training'],
    ['dance', 'ballet', 'hip-hop', 'salsa', 'contemporary', 'tap dancing', 'flamenco', 'breakdancing', 'ballroom', 'belly dancing'],
    ['travel', 'backpacking', 'photography', 'exploring', 'sightseeing', 'cultural immersion', 'hiking', 'road trips', 'adventure', 'beach'],
    ['collecting', 'stamps', 'coins', 'vintage', 'comic books', 'trading cards', 'antiques', 'postcards', 'action figures', 'vinyl records'],
    ['photography', 'landscape', 'portrait', 'street', 'wildlife', 'macro', 'black and white', 'fashion', 'architecture', 'night'],
    ['woodworking', 'carpentry', 'furniture', 'woodturning', 'cabinetmaking', 'wood carving', 'scroll sawing', 'wood burning', 'marquetry', 'intarsia'],
    ['volunteering', 'community', 'animal shelter', 'environmental', 'teaching', 'youth mentoring', 'elderly care', 'disaster relief', 'human rights', 'homelessness'],
    ['languages', 'spanish', 'french', 'german', 'japanese', 'chinese', 'italian', 'arabic', 'russian', 'portuguese'],
    ['fashion', 'design', 'styling', 'sewing', 'knitting', 'upcycling', 'accessories', 'jewelry', 'embroidery', 'textile'],
    ['diy', 'home improvement', 'upcycling', 'crafting', 'painting', 'upholstery', 'electronics', 'home decor', 'gardening', 'plumbing'],
    ['comedy', 'stand-up', 'improv', 'sketch', 'parody', 'slapstick', 'satire', 'comedy writing', 'pranks', 'jokes'],
    ['science', 'astronomy', 'chemistry', 'physics', 'biology', 'geology', 'environmental', 'psychology', 'meteorology', 'neuroscience'],
    ['technology', 'coding', 'robotics', 'web development', 'data analysis', 'cybersecurity', 'artificial intelligence', 'virtual reality', 'blockchain', 'automation'],
    ['film', 'acting', 'directing', 'screenwriting', 'film production', 'cinematography', 'editing', 'special effects', 'documentary', 'animation'],
    ['cycling', 'mountain biking', 'road cycling', 'bmx', 'cyclocross', 'commuting', 'trials riding', 'track cycling', 'recumbent cycling', 'unicycling'],
    ['astrology', 'horoscope', 'tarot', 'numerology', 'palmistry', 'crystal healing', 'divination', 'zodiac signs', 'birth chart', 'spirituality'],
    ['chess', 'strategy', 'tactics', 'puzzles', 'blitz', 'endgame', 'openings', 'online chess', 'chess tournaments', 'chess variants'],
    ['modeling', 'fashion', 'photographic', 'runway', 'commercial', 'fitness', 'plus-size', 'glamour', 'swimsuit', 'artistic'],
    ['sewing', 'quilting', 'embroidery', 'cross-stitch', 'dressmaking', 'knitting', 'crocheting', 'upholstery', 'patchwork', 'soft toys'],
    ['calligraphy', 'hand lettering', 'brush pen', 'copperplate', 'modern', 'gothic', 'italic', 'uncial', 'roman', 'kufic'],
    ['wine', 'tasting', 'pairing', 'winemaking', 'vineyard tours', 'wine festivals', 'wine and food pairing', 'wine education', 'wine collecting', 'wine appreciation'],
    ['gardening', 'flower', 'vegetable', 'herb', 'bonsai', 'succulent', 'indoor', 'permaculture', 'hydroponics', 'landscape'],
    ['writing', 'fiction', 'poetry', 'journaling', 'blogging', 'screenwriting', 'copywriting', 'editing', 'publishing', 'storytelling'],
    ['board games', 'strategy', 'party', 'cooperative', 'card games', 'word games', 'tile games', 'dice games', 'puzzle games', 'classic games'],
    ['painting', 'acrylic', 'watercolor', 'oil', 'abstract', 'landscape', 'portrait', 'still life', 'figurative', 'plein air'],
    ['fitness classes', 'zumba', 'pilates', 'kickboxing', 'bootcamp', 'crossfit', 'aerobics', 'yoga', 'spinning', 'strength training'],
    ['dance', 'ballet', 'hip-hop', 'salsa', 'jazz', 'contemporary', 'tap', 'flamenco', 'breakdancing', 'ballroom'],
    ['writing', 'fiction', 'poetry', 'journaling', 'screenwriting', 'copywriting', 'editing', 'publishing', 'storytelling', 'creative'],
    ['model building', 'planes', 'cars', 'ships', 'trains', 'rockets', 'robots', 'dioramas', 'figurines', 'architecture'],
    ['photography', 'landscape', 'portrait', 'street', 'macro', 'blackandwhite', 'nature', 'architecture', 'wildlife', 'longexposure'],
    ['woodworking', 'carpentry', 'furniture', 'cabinetry', 'woodcarving', 'woodturning', 'scrollsawing', 'woodburning', 'joinery', 'marquetry'],
    ['volunteering', 'community', 'environmental', 'teaching', 'animal', 'youth', 'elderly', 'humanitarian', 'homelessness', 'disaster'],
    ['languages', 'spanish', 'french', 'german', 'japanese', 'chinese', 'italian', 'portuguese', 'arabic', 'russian'],
    ['fashion', 'design', 'styling', 'sewing', 'knitting', 'upcycling', 'accessories', 'jewelry', 'textile', 'embroidery'],
    ['diyprojects', 'renovation', 'upcycling', 'crafting', 'painting', 'upholstery', 'electronics', 'homeimprovement', 'gardening', 'plumbing'],
    ['comedy', 'standup', 'improv', 'sketch', 'parody', 'slapstick', 'satire', 'jokes', 'humor', 'wit'],
    ['science', 'astronomy', 'chemistry', 'physics', 'biology', 'geology', 'psychology', 'environmental', 'sociology', 'anthropology'],
    ['technology', 'coding', 'robotics', 'appdevelopment', 'datascience', 'cybersecurity', 'artificialintelligence', 'automation', 'gamedevelopment', 'blockchain'],
    ['film', 'acting', 'directing', 'screenwriting', 'cinematography', 'editing', 'production', 'animation', 'documentary', 'filmhistory'],
    ['cycling', 'mountainbiking', 'roadcycling', 'bmx', 'commuting', 'trials', 'cyclocross', 'trackcycling', 'unicycling', 'downhill'],
    ['astrology', 'horoscope', 'tarot', 'numerology', 'palmistry', 'divination', 'zodiac', 'spirituality', 'cosmic', 'alignment'],
    ['chess', 'strategy', 'tactics', 'puzzles', 'endgame', 'blitz', 'openings', 'chessvariants', 'onlinechess', 'tournaments'],
    ['modeling', 'fashion', 'photographic', 'runway', 'commercial', 'fitness', 'glamour', 'catalog', 'editorial', 'swimsuit'],
    ['sewing', 'quilting', 'embroidery', 'crocheting', 'knitting', 'crossstitch', 'dressmaking', 'upholstery', 'patchwork', 'handmade'],
    ['calligraphy', 'handlettering', 'brushpen', 'modern', 'gothic', 'copperplate', 'italic', 'uncial', 'blackletter', 'serif'],
    ['wine', 'tasting', 'pairing', 'oenology', 'viticulture', 'sommelier', 'wineproduction', 'winecollecting', 'winemaking', 'wineeducation'],
    ['gardening', 'flower', 'vegetable', 'herb', 'permaculture', 'bonsai', 'succulent', 'landscape', 'orchids', 'composting'],
    ['writing', 'fiction', 'poetry', 'journaling', 'blogging', 'copywriting', 'editing', 'publishing', 'creativewriting', 'storytelling'],
    ['boardgames', 'strategy', 'party', 'cardgames', 'puzzlegames', 'wordgames', 'cooperative', 'deckbuilding', 'tilegames', 'classicgames'],
    ['painting', 'acrylic', 'watercolor', 'oil', 'abstract', 'landscape', 'portrait', 'figurative', 'stilllife', 'impressionism'],
    ['fitnessclasses', 'zumba', 'pilates', 'yoga', 'kickboxing', 'spinning', 'aerobics', 'crossfit', 'barre', 'trx'],
    ['dance', 'ballet', 'hiphop', 'salsa', 'contemporary', 'jazz', 'tapdance', 'flamenco', 'ballroom', 'breakdance'],
    ['writing', 'fiction', 'poetry', 'journaling', 'screenwriting', 'copywriting', 'editing', 'publishing', 'blogging', 'creativity'],
    ['modelbuilding', 'aircraft', 'cars', 'trains', 'ships', 'dioramas', 'miniatures', 'rcmodels', 'sci-fi', 'military'],
    ['beading', 'jewelrymaking', 'wirewrapping', 'beadweaving', 'macrame', 'pearlknitting', 'stringing', 'polymerclay', 'resin', 'embellishments']
]

algorithm_categories = [
    ['Bubble Sort', 'Selection Sort', 'Insertion Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort', 'Radix Sort'],
    ['Linear Search', 'Binary Search', 'Depth-First Search (DFS)', 'Breadth-First Search (BFS)'],
    ['Dijkstra\'s Algorithm', 'Prim\'s Algorithm', 'Kruskal\'s Algorithm', 'Bellman-Ford Algorithm', 'Floyd-Warshall Algorithm'],
    ['Linear Regression', 'Logistic Regression', 'Decision Trees', 'Random Forests', 'Support Vector Machines (SVM)', 'K-Nearest Neighbors (KNN)', 'Naive Bayes', 'Neural Networks'],
    ['Convex Hull Algorithms', 'Line Intersection Algorithms', 'Closest Pair Algorithms'],
    ['Huffman Coding', 'Lempel-Ziv-Welch (LZW) Compression', 'Run-Length Encoding (RLE)'],
    ['RSA Encryption', 'AES (Advanced Encryption Standard)', 'SHA (Secure Hash Algorithm)', 'Diffie-Hellman Key Exchange'],
    ['Edge Detection', 'Image Filtering', 'Image Segmentation'],
    ['Knapsack Problem', 'Longest Common Subsequence', 'Fibonacci Sequence'],
    ['Newton-Raphson Method', 'Sieve of Eratosthenes', 'Gaussian Elimination'],
    ['Smith-Waterman Algorithm', 'Needleman-Wunsch Algorithm', 'Hidden Markov Models'],
    ['Stacks', 'Queues', 'Linked Lists', 'Hash Tables', 'Binary Trees', 'Graphs'],
    ['Routing Algorithms', 'Max Flow Algorithms', 'Spanning Tree Algorithms'],
    ['N-gram Models', 'Hidden Markov Models', 'Word Embeddings'],
    ['Collaborative Filtering', 'Content-Based Filtering', 'Matrix Factorization'],
    ['Minimax Algorithm', 'Alpha-Beta Pruning', 'Monte Carlo Tree Search'],
    ['Knuth-Morris-Pratt Algorithm', 'Boyer-Moore Algorithm', 'Rabin-Karp Algorithm'],
    ['Randomized Quick Sort', 'Randomized Prim\'s Algorithm', 'Las Vegas Algorithms'],
    ['Consensus Algorithms', 'Distributed Hash Tables (DHT)', 'Byzantine Fault Tolerance (BFT)'],
    ['B-Tree', 'Hash Indexing', 'Join Algorithms'],
    ['Online Convex Optimization', 'Competitive Analysis', 'Online Learning'],
    ['K-Means Clustering', 'DBSCAN', 'Hierarchical Clustering'],
    ['Principal Component Analysis (PCA)', 't-SNE', 'Non-negative Matrix Factorization'],
    ['Minimax Algorithm', 'Alpha-Beta Pruning', 'Monte Carlo Tree Search'],
    ['Longest Common Subsequence', 'Levenshtein Distance', 'Trie'],
    ['Matrix Multiplication', 'Matrix Inversion', 'Eigenvalue Decomposition'],
    ['Parallel Sorting Algorithms', 'Parallel Matrix Multiplication', 'Parallel Breadth-First Search'],
    ['Q-Learning', 'Deep Q-Networks (DQN)', 'Policy Gradient'],
    ['Genetic Algorithms', 'Particle Swarm Optimization (PSO)', 'Ant Colony Optimization'],
    ['Community Detection', 'Centrality Measures', 'Link Prediction'],
    ['Simulated Annealing', 'Genetic Algorithms', 'Particle Swarm Optimization (PSO)']
]

data_structure_categories = [
    ['Array', 'Linked List'],
    ['Stack', 'Queue', 'Double-Ended Priority Queue', 'Deque', 'Circular Buffer'],
    ['Hash Table', 'Hash Set', 'Hash Map', 'Hash Tree', 'Hash Array Mapped Trie (HAMT)'],
    ['Trie', 'Patricia Trie', 'Suffix Trie', 'Trie'],
    ['Binary Tree', 'Binary Search Tree', 'AVL Tree', 'Red-Black Tree', 'Splay Tree', 'Treap', 'Cartesian Tree', 'B-Tree', 'Quadtree', 'KD-Tree', 'Interval Tree', 'Van Emde Boas Tree', 'Segment Tree', 'Fenwick Tree', 'Binary Indexed Tree (BIT)', 'Tree'],
    ['Heap', 'Priority Queue', 'Fibonacci Heap', 'Binomial Heap', 'Pairing Heap', 'Leftist Heap', 'Skew Heap', 'Brodal Queue', 'Soft Heap', 'Heap'],
    ['Graph', 'Adjacency List', 'Adjacency Matrix', 'Incidence Matrix', 'Edge List'],
]
