# Generated by Django 4.2.1 on 2023-05-23 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('programming_language', models.CharField(max_length=10)),
                ('university_specialization', models.CharField(max_length=10)),
                ('course_fav1', models.CharField(max_length=10)),
                ('course_fav2', models.CharField(max_length=10)),
                ('course_fav3', models.CharField(max_length=10)),
                ('hobby1', models.CharField(max_length=15)),
                ('hobby2', models.CharField(max_length=15)),
                ('hobby3', models.CharField(max_length=15)),
                ('hobby4', models.CharField(max_length=15)),
                ('hobby5', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN'), ('-', 'UNKNOWN')], default='-', max_length=1)),
                ('interest', models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN'), ('-', 'UNKNOWN')], default='-', max_length=1)),
                ('favorite_algorithm', models.CharField(max_length=15)),
                ('favorite_data_structure', models.CharField(max_length=15)),
                ('short_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('password', models.CharField(max_length=100)),
                ('isBanned', models.BooleanField(default=False)),
                ('role', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('formId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.form')),
                ('matchId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
    ]
