# Generated by Django 4.2.1 on 2023-05-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('OPN', 'OPEN'), ('CSD', 'CLOSED')], default='OPN', max_length=3)),
                ('receiverID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
    ]
