# Generated by Django 4.2.1 on 2023-05-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_report_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='interest',
            field=models.CharField(choices=[('F', 'FEMININ'), ('M', 'MASCULIN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='formId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.form'),
        ),
    ]
