# Generated by Django 4.2.1 on 2023-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_dateoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matchId',
        ),
        migrations.AddField(
            model_name='user',
            name='matchId',
            field=models.ManyToManyField(blank=True, null=True, related_name='followings', to='application.user'),
        ),
    ]
