# Generated by Django 4.2.1 on 2023-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_user_matchid_user_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matchId',
            field=models.ManyToManyField(related_name='followings', to='application.user'),
        ),
    ]
