# Generated by Django 4.2.1 on 2023-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_user_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='favorite_algorithm',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='favorite_data_structure',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='interest',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1),
        ),
    ]
