# Generated by Django 4.2.1 on 2023-11-05 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_form_favorite_algorithm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverIdRate', to='application.user')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderIdRate', to='application.user')),
            ],
        ),
    ]
