# Generated by Django 4.2.1 on 2023-11-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_ratedate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedate',
            name='receiverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiverIdRate', to='application.user'),
        ),
        migrations.AlterField(
            model_name='ratedate',
            name='senderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senderIdRate', to='application.user'),
        ),
    ]
